[theme]
primaryColor = "#004B73"
backgroundColor = "#F4F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E293B"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
enableStaticServing = true
enableXsrfProtection = true
enableCORS = true
maxUploadSize = 5
headless = true
# Force rebuild: 2026-09-20 16:22
